export const GET_DAILY_REPORT = 'GET_DAILY_REPORT';
export const GET_COUNTRY_REPORT = 'GET_COUNTRY_REPORT';
export const GET_COUNTRY_DAILY_REPORT = 'GET_COUNTRY_DAILY_REPORT';

export const USER_LOADING = 'USER_LOADING'; 
export const USER_LOADED = 'USER_LOADED'; 
export const AUTH_ERROR = 'AUTH_ERROR'; 
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'; 
export const REGISTER_FAIL = 'REGISTER_FAIL'; 
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'; 
export const LOGIN_FAIL = 'LOGIN_FAIL'; 
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'; 